<a href="https://colab.research.google.com/github/lapatradaa/python_dataviz2023/blob/main/Pandas102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os

In [2]:
from google.colab import drive # เชื่อมบัญชีกับ google drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx')
sep_df

,เป้าหมายการเบิกจ่ายและการใช้จ่ายงบประมาณ พ.ศ. 2565,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,รายการ,ไตรมาสที่ 1,NaN,ไตรมาสที่ 2,NaN,ไตรมาสที่ 3,NaN,ไตรมาสที่ 4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,เบิกจ่าย,ใช้จ่าย,เบิกจ่าย,ใช้จ่าย,เบิกจ่าย,ใช้จ่าย,เบิกจ่าย,ใช้จ่าย,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ภาพรวม,30,34.08,51,56.24,72,81.74,93,100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ประจำ,34,35.33,57,55.78,79,81.76,98,100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ลงทุน,13,28.96,29,58.15,46,81.65,75,100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ผลการใช้จ่ายงบประมาณรายจ่ายจังหวัดเชียงใหม่ ปร...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q4,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,...,ลำดับ\nใช้จ่าย,NaN,รายการ,งบประมาณ,ผลเบิกจ่าย,ร้อยละเบิกจ่าย,สูงกว่าเป้าหมาย,ผลการใช้จ่าย,ร้อยละ,สูงกว่าเป้าหมาย
8,งบประมาณรายจ่ายประจำปี พ.ศ.2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ไตรมาส 2,(PO + เบิกจ่าย),การใช้จ่าย,ไตรมาส 2
9,ภาพรวม,28525389387.86998,347600454.93,1190636149.69,27003921829.55999,94.666269,93,1.666269,28542158434.179993,100.058786,...,51,3,ภาพรวม,21663.922002,15260.448175,70.441761,19.441761,18069.314644,83.407403,27.167403
10,ประจำ,18920131432.719986,79257448.41,71316001.06,18801957159.449989,99.375405,98,1.375405,18952530608.919991,100.171242,...,NaN,NaN,ประจำ,12452.79457,10580.839075,84.967587,27.967587,10614.976114,85.241719,29.461719
11,ลงทุน,9605257955.149996,268343006.52,1119320148.63,8201964670.11,85.390363,75,10.390363,9589627825.26,99.837275,...,15,13,ลงทุน,9211.127432,4679.6091,50.803869,21.803869,7454.33853,80.927537,22.777537
12,ค่าใช้จ่ายบรรเทาผลกระทบจากการแพร่ระบาดของ COVI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,ภาพรวม,2997790719.61,55485.83,28344424.87,2786219946.98,92.942444,NaN,NaN,2814619857.68,93.889805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,เงินกู้,2461860887.43,0,28344424.87,2256794827.16,91.670282,NaN,NaN,2285139252.03,92.821624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ปี 2563,24020888.32,0,0,24020888.32,100,NaN,NaN,24020888.32,100,...,NaN,NaN,NaN,ปี งปม.,จำนวน (ลบ.),ผลใช้จ่าย (ลบ.),NaN,NaN,NaN,NaN
16,ปี 2564,1772476259.27,0,1059233.4,1701880930.48,96.017135,NaN,NaN,1702940163.88,96.076896,...,NaN,NaN,NaN,63,25.88,92.8,NaN,NaN,NaN,NaN
17,ปี 2565,665363739.84,0,27285191.47,530893008.36,79.789892,NaN,NaN,558178199.83,83.890685,...,NaN,NaN,NaN,64,1778.64,95.75,NaN,NaN,NaN,NaN
18,งบกลาง,535929832.18,55485.83,0,529425119.82,98.786275,NaN,NaN,529480605.65,98.796629,...,NaN,NaN,NaN,65,668.82,88.71,NaN,NaN,NaN,NaN
19,ปี 2564,384191433.43,55485.83,0,379138167.2,98.684701,NaN,NaN,379193653.03,98.699143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,ปี 2565,151738398.75,0,0,150286952.62,99.043455,NaN,NaN,150286952.62,99.043455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,งบกลาง เงินสำรองจ่ายเพื่อกรณีฉุกเฉินหรือจำเป็น,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,งบประมาณเหลื่อมปี,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,งบกลาง,337.55,90.9,NaN,NaN,NaN,NaN
24,รายการ,งบประมาณ,สำรองเงิน\nแบบมีหนี้\nเหลื่อมปี อนุมัติ,ใบสั่งซื้อ\nเหลื่อมปี\nอนุมัติ,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,NaN,NaN,การใช่จ่าย,ร้อยละ\nการใช้จ่าย,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,ปี 64,2332331126.399999,0,69727138.69,2161354074.1,92.669263,NaN,NaN,2231081212.79,95.658853,...,NaN,NaN,NaN,รวม,2810.89,88.98,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,งบกรมจังหวัด,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,งบกลุ่มจังหวัดภาคเหนือตอนบน 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,ภาพรวม,88.1266,NaN,65.132317,17.083368,19.38503,93,-73.61497,82.215685,93.292701,...,NaN,18มีค,6.707299,73.61497,NaN,NaN,NaN,NaN,NaN,NaN
30,ประจำ,22.3025,NaN,6.345138,10.370555,46.499518,98,-51.500482,16.715693,74.949863,...,NaN,NaN,25.050137,51.500482,NaN,NaN,NaN,NaN,NaN,NaN
31,ลงทุน,65.8241,NaN,58.787179,6.712813,10.198108,75,-64.801892,65.499992,99.507615,...,NaN,NaN,0.492385,64.801892,NaN,NaN,NaN,NaN,NaN,NaN
32,งบพัฒนาจังหวัด,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
33,ภาพรวม,302.5171,NaN,81.666079,184.515266,60.993334,93,-32.006666,266.181345,87.988859,...,NaN,NaN,12.011141,32.006666,NaN,NaN,NaN,NaN,NaN,NaN
34,ประจำ,31.1817,NaN,2.636562,16.719159,53.618497,98,-44.381503,19.355721,62.073975,...,NaN,NaN,37.926025,44.381503,NaN,NaN,NaN,NaN,NaN,NaN
35,ลงทุน,271.3354,NaN,79.029517,167.796107,61.840846,75,-13.159154,246.825624,90.966982,...,NaN,NaN,9.033018,13.159154,NaN,NaN,NaN,NaN,NaN,NaN
36,ที่มา : ระบบการบริหารการเงินการคลังภาครัฐแบบอิ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,ข้อมูล ณ 30 กันยายน 2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx',header=8,skiprows=2)
sep_df

,ภาพรวม,28525389387.86998,347600454.93,1190636149.69,27003921829.55999,94.66626892407305,93,1.6662689240730515,28542158434.179993,100.05878638879209,...,51,3,ภาพรวม.1,21663.922001990002,15260.44817453,70.44176106767836,19.441761067678357,18069.31464446,83.40740260604792,27.167402606047922
0,ประจำ,18920131432.719986,79257448.41,71316001.06,18801957159.449989,99.375405,98.0,1.375405,18952530608.919991,100.171242,...,NaN,NaN,ประจำ,12452.79457,10580.839075,84.967587,27.967587,10614.976114,85.241719,29.461719
1,ลงทุน,9605257955.149996,268343006.52,1119320148.63,8201964670.11,85.390363,75.0,10.390363,9589627825.26,99.837275,...,15.0,13,ลงทุน,9211.127432,4679.6091,50.803869,21.803869,7454.338530,80.927537,22.777537
2,ค่าใช้จ่ายบรรเทาผลกระทบจากการแพร่ระบาดของ COVI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ภาพรวม,2997790719.61,55485.83,28344424.87,2786219946.98,92.942444,NaN,NaN,2814619857.68,93.889805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,เงินกู้,2461860887.43,0,28344424.87,2256794827.16,91.670282,NaN,NaN,2285139252.03,92.821624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ปี 2563,24020888.32,0,0,24020888.32,100,NaN,NaN,24020888.32,100,...,NaN,NaN,NaN,ปี งปม.,จำนวน (ลบ.),ผลใช้จ่าย (ลบ.),NaN,NaN,NaN,NaN
6,ปี 2564,1772476259.27,0,1059233.4,1701880930.48,96.017135,NaN,NaN,1702940163.88,96.076896,...,NaN,NaN,NaN,63,25.88,92.8,NaN,NaN,NaN,NaN
7,ปี 2565,665363739.84,0,27285191.47,530893008.36,79.789892,NaN,NaN,558178199.83,83.890685,...,NaN,NaN,NaN,64,1778.64,95.75,NaN,NaN,NaN,NaN
8,งบกลาง,535929832.18,55485.83,0,529425119.82,98.786275,NaN,NaN,529480605.65,98.796629,...,NaN,NaN,NaN,65,668.82,88.71,NaN,NaN,NaN,NaN
9,ปี 2564,384191433.43,55485.83,0,379138167.2,98.684701,NaN,NaN,379193653.03,98.699143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,ปี 2565,151738398.75,0,0,150286952.62,99.043455,NaN,NaN,150286952.62,99.043455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,งบกลาง เงินสำรองจ่ายเพื่อกรณีฉุกเฉินหรือจำเป็น,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,งบประมาณเหลื่อมปี,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,งบกลาง,337.55,90.9,NaN,NaN,NaN,NaN
14,รายการ,งบประมาณ,สำรองเงิน\nแบบมีหนี้\nเหลื่อมปี อนุมัติ,ใบสั่งซื้อ\nเหลื่อมปี\nอนุมัติ,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,NaN,NaN,การใช่จ่าย,ร้อยละ\nการใช้จ่าย,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ปี 64,2332331126.399999,0,69727138.69,2161354074.1,92.669263,NaN,NaN,2231081212.79,95.658853,...,NaN,NaN,NaN,รวม,2810.89,88.98,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,งบกรมจังหวัด,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,งบกลุ่มจังหวัดภาคเหนือตอนบน 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ภาพรวม,88.1266,NaN,65.132317,17.083368,19.38503,93.0,-73.614970,82.215685,93.292701,...,NaN,18มีค,6.707299,73.61497,NaN,NaN,NaN,NaN,NaN,NaN
20,ประจำ,22.3025,NaN,6.345138,10.370555,46.499518,98.0,-51.500482,16.715693,74.949863,...,NaN,NaN,25.050137,51.500482,NaN,NaN,NaN,NaN,NaN,NaN
21,ลงทุน,65.8241,NaN,58.787179,6.712813,10.198108,75.0,-64.801892,65.499992,99.507615,...,NaN,NaN,0.492385,64.801892,NaN,NaN,NaN,NaN,NaN,NaN
22,งบพัฒนาจังหวัด,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
23,ภาพรวม,302.5171,NaN,81.666079,184.515266,60.993334,93.0,-32.006666,266.181345,87.988859,...,NaN,NaN,12.011141,32.006666,NaN,NaN,NaN,NaN,NaN,NaN
24,ประจำ,31.1817,NaN,2.636562,16.719159,53.618497,98.0,-44.381503,19.355721,62.073975,...,NaN,NaN,37.926025,44.381503,NaN,NaN,NaN,NaN,NaN,NaN
25,ลงทุน,271.3354,NaN,79.029517,167.796107,61.840846,75.0,-13.159154,246.825624,90.966982,...,NaN,NaN,9.033018,13.159154,NaN,NaN,NaN,NaN,NaN,NaN
26,ที่มา : ระบบการบริหารการเงินการคลังภาครัฐแบบอิ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,ข้อมูล ณ 30 กันยายน 2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
sep_df.head() # ดูหัวตารางแถวบน

,ภาพรวม,28525389387.86998,347600454.93,1190636149.69,27003921829.55999,94.66626892407305,93,1.6662689240730515,28542158434.179993,100.05878638879209,...,51,3,ภาพรวม.1,21663.922001990002,15260.44817453,70.44176106767836,19.441761067678357,18069.31464446,83.40740260604792,27.167402606047922
0,ประจำ,18920131432.719986,79257448.41,71316001.06,18801957159.449989,99.375405,98.0,1.375405,18952530608.919991,100.171242,...,NaN,NaN,ประจำ,12452.79457,10580.839075,84.967587,27.967587,10614.976114,85.241719,29.461719
1,ลงทุน,9605257955.149996,268343006.52,1119320148.63,8201964670.11,85.390363,75.0,10.390363,9589627825.26,99.837275,...,15.0,13,ลงทุน,9211.127432,4679.6091,50.803869,21.803869,7454.338530,80.927537,22.777537
2,ค่าใช้จ่ายบรรเทาผลกระทบจากการแพร่ระบาดของ COVI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ภาพรวม,2997790719.61,55485.83,28344424.87,2786219946.98,92.942444,NaN,NaN,2814619857.68,93.889805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,เงินกู้,2461860887.43,0,28344424.87,2256794827.16,91.670282,NaN,NaN,2285139252.03,92.821624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx', header=8)
sep_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q4,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,...,ลำดับ\nใช้จ่าย,Unnamed: 15,รายการ.1,งบประมาณ.1,ผลเบิกจ่าย,ร้อยละเบิกจ่าย,สูงกว่าเป้าหมาย,ผลการใช้จ่าย,ร้อยละ,สูงกว่าเป้าหมาย.1
0,งบประมาณรายจ่ายประจำปี พ.ศ.2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ไตรมาส 2,(PO + เบิกจ่าย),การใช้จ่าย,ไตรมาส 2
1,ภาพรวม,28525389387.86998,347600454.93,1190636149.69,27003921829.55999,94.666269,93.0,1.666269,28542158434.179993,100.058786,...,51.0,3,ภาพรวม,21663.922002,15260.448175,70.441761,19.441761,18069.314644,83.407403,27.167403
2,ประจำ,18920131432.719986,79257448.41,71316001.06,18801957159.449989,99.375405,98.0,1.375405,18952530608.919991,100.171242,...,NaN,NaN,ประจำ,12452.79457,10580.839075,84.967587,27.967587,10614.976114,85.241719,29.461719
3,ลงทุน,9605257955.149996,268343006.52,1119320148.63,8201964670.11,85.390363,75.0,10.390363,9589627825.26,99.837275,...,15.0,13,ลงทุน,9211.127432,4679.6091,50.803869,21.803869,7454.33853,80.927537,22.777537
4,ค่าใช้จ่ายบรรเทาผลกระทบจากการแพร่ระบาดของ COVI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ภาพรวม,2997790719.61,55485.83,28344424.87,2786219946.98,92.942444,NaN,NaN,2814619857.68,93.889805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,เงินกู้,2461860887.43,0,28344424.87,2256794827.16,91.670282,NaN,NaN,2285139252.03,92.821624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ปี 2563,24020888.32,0,0,24020888.32,100,NaN,NaN,24020888.32,100,...,NaN,NaN,NaN,ปี งปม.,จำนวน (ลบ.),ผลใช้จ่าย (ลบ.),NaN,NaN,NaN,NaN
8,ปี 2564,1772476259.27,0,1059233.4,1701880930.48,96.017135,NaN,NaN,1702940163.88,96.076896,...,NaN,NaN,NaN,63,25.88,92.8,NaN,NaN,NaN,NaN
9,ปี 2565,665363739.84,0,27285191.47,530893008.36,79.789892,NaN,NaN,558178199.83,83.890685,...,NaN,NaN,NaN,64,1778.64,95.75,NaN,NaN,NaN,NaN
10,งบกลาง,535929832.18,55485.83,0,529425119.82,98.786275,NaN,NaN,529480605.65,98.796629,...,NaN,NaN,NaN,65,668.82,88.71,NaN,NaN,NaN,NaN
11,ปี 2564,384191433.43,55485.83,0,379138167.2,98.684701,NaN,NaN,379193653.03,98.699143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ปี 2565,151738398.75,0,0,150286952.62,99.043455,NaN,NaN,150286952.62,99.043455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,งบกลาง เงินสำรองจ่ายเพื่อกรณีฉุกเฉินหรือจำเป็น,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,งบประมาณเหลื่อมปี,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,งบกลาง,337.55,90.9,NaN,NaN,NaN,NaN
16,รายการ,งบประมาณ,สำรองเงิน\nแบบมีหนี้\nเหลื่อมปี อนุมัติ,ใบสั่งซื้อ\nเหลื่อมปี\nอนุมัติ,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,NaN,NaN,การใช่จ่าย,ร้อยละ\nการใช้จ่าย,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,ปี 64,2332331126.399999,0,69727138.69,2161354074.1,92.669263,NaN,NaN,2231081212.79,95.658853,...,NaN,NaN,NaN,รวม,2810.89,88.98,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,งบกรมจังหวัด,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,งบกลุ่มจังหวัดภาคเหนือตอนบน 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,ภาพรวม,88.1266,NaN,65.132317,17.083368,19.38503,93.0,-73.614970,82.215685,93.292701,...,NaN,18มีค,6.707299,73.61497,NaN,NaN,NaN,NaN,NaN,NaN
22,ประจำ,22.3025,NaN,6.345138,10.370555,46.499518,98.0,-51.500482,16.715693,74.949863,...,NaN,NaN,25.050137,51.500482,NaN,NaN,NaN,NaN,NaN,NaN
23,ลงทุน,65.8241,NaN,58.787179,6.712813,10.198108,75.0,-64.801892,65.499992,99.507615,...,NaN,NaN,0.492385,64.801892,NaN,NaN,NaN,NaN,NaN,NaN
24,งบพัฒนาจังหวัด,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
25,ภาพรวม,302.5171,NaN,81.666079,184.515266,60.993334,93.0,-32.006666,266.181345,87.988859,...,NaN,NaN,12.011141,32.006666,NaN,NaN,NaN,NaN,NaN,NaN
26,ประจำ,31.1817,NaN,2.636562,16.719159,53.618497,98.0,-44.381503,19.355721,62.073975,...,NaN,NaN,37.926025,44.381503,NaN,NaN,NaN,NaN,NaN,NaN
27,ลงทุน,271.3354,NaN,79.029517,167.796107,61.840846,75.0,-13.159154,246.825624,90.966982,...,NaN,NaN,9.033018,13.159154,NaN,NaN,NaN,NaN,NaN,NaN
28,ที่มา : ระบบการบริหารการเงินการคลังภาครัฐแบบอิ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,ข้อมูล ณ 30 กันยายน 2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx', header=8, skiprows=2)
sep_df

,ภาพรวม,28525389387.86998,347600454.93,1190636149.69,27003921829.55999,94.66626892407305,93,1.6662689240730515,28542158434.179993,100.05878638879209,...,51,3,ภาพรวม.1,21663.922001990002,15260.44817453,70.44176106767836,19.441761067678357,18069.31464446,83.40740260604792,27.167402606047922
0,ประจำ,18920131432.719986,79257448.41,71316001.06,18801957159.449989,99.375405,98.0,1.375405,18952530608.919991,100.171242,...,NaN,NaN,ประจำ,12452.79457,10580.839075,84.967587,27.967587,10614.976114,85.241719,29.461719
1,ลงทุน,9605257955.149996,268343006.52,1119320148.63,8201964670.11,85.390363,75.0,10.390363,9589627825.26,99.837275,...,15.0,13,ลงทุน,9211.127432,4679.6091,50.803869,21.803869,7454.338530,80.927537,22.777537
2,ค่าใช้จ่ายบรรเทาผลกระทบจากการแพร่ระบาดของ COVI...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ภาพรวม,2997790719.61,55485.83,28344424.87,2786219946.98,92.942444,NaN,NaN,2814619857.68,93.889805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,เงินกู้,2461860887.43,0,28344424.87,2256794827.16,91.670282,NaN,NaN,2285139252.03,92.821624,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ปี 2563,24020888.32,0,0,24020888.32,100,NaN,NaN,24020888.32,100,...,NaN,NaN,NaN,ปี งปม.,จำนวน (ลบ.),ผลใช้จ่าย (ลบ.),NaN,NaN,NaN,NaN
6,ปี 2564,1772476259.27,0,1059233.4,1701880930.48,96.017135,NaN,NaN,1702940163.88,96.076896,...,NaN,NaN,NaN,63,25.88,92.8,NaN,NaN,NaN,NaN
7,ปี 2565,665363739.84,0,27285191.47,530893008.36,79.789892,NaN,NaN,558178199.83,83.890685,...,NaN,NaN,NaN,64,1778.64,95.75,NaN,NaN,NaN,NaN
8,งบกลาง,535929832.18,55485.83,0,529425119.82,98.786275,NaN,NaN,529480605.65,98.796629,...,NaN,NaN,NaN,65,668.82,88.71,NaN,NaN,NaN,NaN
9,ปี 2564,384191433.43,55485.83,0,379138167.2,98.684701,NaN,NaN,379193653.03,98.699143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,ปี 2565,151738398.75,0,0,150286952.62,99.043455,NaN,NaN,150286952.62,99.043455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,งบกลาง เงินสำรองจ่ายเพื่อกรณีฉุกเฉินหรือจำเป็น,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,งบประมาณเหลื่อมปี,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,งบกลาง,337.55,90.9,NaN,NaN,NaN,NaN
14,รายการ,งบประมาณ,สำรองเงิน\nแบบมีหนี้\nเหลื่อมปี อนุมัติ,ใบสั่งซื้อ\nเหลื่อมปี\nอนุมัติ,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,NaN,NaN,การใช่จ่าย,ร้อยละ\nการใช้จ่าย,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ปี 64,2332331126.399999,0,69727138.69,2161354074.1,92.669263,NaN,NaN,2231081212.79,95.658853,...,NaN,NaN,NaN,รวม,2810.89,88.98,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,งบกรมจังหวัด,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,งบกลุ่มจังหวัดภาคเหนือตอนบน 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ภาพรวม,88.1266,NaN,65.132317,17.083368,19.38503,93.0,-73.614970,82.215685,93.292701,...,NaN,18มีค,6.707299,73.61497,NaN,NaN,NaN,NaN,NaN,NaN
20,ประจำ,22.3025,NaN,6.345138,10.370555,46.499518,98.0,-51.500482,16.715693,74.949863,...,NaN,NaN,25.050137,51.500482,NaN,NaN,NaN,NaN,NaN,NaN
21,ลงทุน,65.8241,NaN,58.787179,6.712813,10.198108,75.0,-64.801892,65.499992,99.507615,...,NaN,NaN,0.492385,64.801892,NaN,NaN,NaN,NaN,NaN,NaN
22,งบพัฒนาจังหวัด,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
23,ภาพรวม,302.5171,NaN,81.666079,184.515266,60.993334,93.0,-32.006666,266.181345,87.988859,...,NaN,NaN,12.011141,32.006666,NaN,NaN,NaN,NaN,NaN,NaN
24,ประจำ,31.1817,NaN,2.636562,16.719159,53.618497,98.0,-44.381503,19.355721,62.073975,...,NaN,NaN,37.926025,44.381503,NaN,NaN,NaN,NaN,NaN,NaN
25,ลงทุน,271.3354,NaN,79.029517,167.796107,61.840846,75.0,-13.159154,246.825624,90.966982,...,NaN,NaN,9.033018,13.159154,NaN,NaN,NaN,NaN,NaN,NaN
26,ที่มา : ระบบการบริหารการเงินการคลังภาครัฐแบบอิ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,ข้อมูล ณ 30 กันยายน 2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx', header=8, skipfooter=26)
sep_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q4,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,...,ลำดับ\nใช้จ่าย,Unnamed: 15,รายการ.1,งบประมาณ.1,ผลเบิกจ่าย,ร้อยละเบิกจ่าย,สูงกว่าเป้าหมาย,ผลการใช้จ่าย,ร้อยละ,สูงกว่าเป้าหมาย.1
0,งบประมาณรายจ่ายประจำปี พ.ศ.2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ไตรมาส 2,(PO + เบิกจ่าย),การใช้จ่าย,ไตรมาส 2
1,ภาพรวม,2.852539e+10,3.476005e+08,1.190636e+09,2.700392e+10,94.666269,93.0,1.666269,2.854216e+10,100.058786,...,51.0,3.0,ภาพรวม,21663.922002,15260.448175,70.441761,19.441761,18069.314644,83.407403,27.167403
2,ประจำ,1.892013e+10,7.925745e+07,7.131600e+07,1.880196e+10,99.375405,98.0,1.375405,1.895253e+10,100.171242,...,NaN,NaN,ประจำ,12452.794570,10580.839075,84.967587,27.967587,10614.976114,85.241719,29.461719
3,ลงทุน,9.605258e+09,2.683430e+08,1.119320e+09,8.201965e+09,85.390363,75.0,10.390363,9.589628e+09,99.837275,...,15.0,13.0,ลงทุน,9211.127432,4679.609100,50.803869,21.803869,7454.33853,80.927537,22.777537

#Quiz 4
ตัดตาราง sep_df ให้เหลือเฉพาะ  15 columns แรก และข้อมูลงบประจำกับงบทุน

In [10]:
drop15sep_df = sep_df.iloc[-2:,:15]
drop15sep_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q4,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,เป้า\nหมาย Q4.1,*/- เป้าหมาย.1,คงเหลือ\nหลังหักใช้จ่าย,ลำดับเบิกจ่าย,ลำดับ\nใช้จ่าย
2,ประจำ,1.892013e+10,7.925745e+07,7.131600e+07,1.880196e+10,99.375405,98.0,1.375405,1.895253e+10,100.171242,100.0,0.171242,-3.239918e+07,NaN,NaN
3,ลงทุน,9.605258e+09,2.683430e+08,1.119320e+09,8.201965e+09,85.390363,75.0,10.390363,9.589628e+09,99.837275,100.0,-0.162725,1.563013e+07,6.0,15.0

In [11]:
drop15sep_df['เดือน-ปี'] = len(drop15sep_df)*['sep-65']
drop15sep_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q4,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,เป้า\nหมาย Q4.1,*/- เป้าหมาย.1,คงเหลือ\nหลังหักใช้จ่าย,ลำดับเบิกจ่าย,ลำดับ\nใช้จ่าย,เดือน-ปี
2,ประจำ,1.892013e+10,7.925745e+07,7.131600e+07,1.880196e+10,99.375405,98.0,1.375405,1.895253e+10,100.171242,100.0,0.171242,-3.239918e+07,NaN,NaN,sep-65
3,ลงทุน,9.605258e+09,2.683430e+08,1.119320e+09,8.201965e+09,85.390363,75.0,10.390363,9.589628e+09,99.837275,100.0,-0.162725,1.563013e+07,6.0,15.0,sep-65

In [12]:
oct_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/oct65.xlsx', header=9, skipfooter=27)
drop15oct_df = oct_df.iloc[-2:,:15]
drop15oct_df['เดือน-ปี'] = len(drop15oct_df)*['oct-65']
drop15oct_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q1,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,เป้า\nหมาย Q1.1,*/- เป้าหมาย.1,คงเหลือ\nหลังหักใช้จ่าย,ลำดับเบิกจ่าย,ลำดับ\nใช้จ่าย,เดือน-ปี
2,ประจำ,6822.811789,NaN,12.706842,3984.779058,58.403766,35.0,23.403766,3997.485900,58.590007,35.33,23.260007,2825.325889,NaN,NaN,oct-65
3,ลงทุน,6180.211723,NaN,457.295806,1291.209026,20.892634,19.0,1.892634,1748.504832,28.291989,28.96,-0.668011,4431.706890,4.0,6.0,oct-65

# ต่อตาราง


*   ต่อในเเนวเเกน Y (เพิ่มจำนวนข้อมูล)
*   ต่อในเเนวเเกน X (เพิ่มรายละเอียดของข้อมูล)

## ต่อตารางแกน Y (แกน rows)

In [13]:
sep_oct_df = pd.concat([sep_df, oct_df])
sep_oct_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q4,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,...,รายการ.1,งบประมาณ.1,ผลเบิกจ่าย,ร้อยละเบิกจ่าย,สูงกว่าเป้าหมาย,ผลการใช้จ่าย,ร้อยละ,สูงกว่าเป้าหมาย.1,เป้า\nหมาย Q1,เป้า\nหมาย Q1.1
0,งบประมาณรายจ่ายประจำปี พ.ศ.2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,ไตรมาส 2,(PO + เบิกจ่าย),การใช้จ่าย,ไตรมาส 2,NaN,NaN
1,ภาพรวม,2.852539e+10,3.476005e+08,1.190636e+09,2.700392e+10,94.666269,93.0,1.666269,2.854216e+10,100.058786,...,ภาพรวม,21663.922002,15260.448175,70.441761,19.441761,18069.314644,83.407403,27.167403,NaN,NaN
2,ประจำ,1.892013e+10,7.925745e+07,7.131600e+07,1.880196e+10,99.375405,98.0,1.375405,1.895253e+10,100.171242,...,ประจำ,12452.794570,10580.839075,84.967587,27.967587,10614.976114,85.241719,29.461719,NaN,NaN
3,ลงทุน,9.605258e+09,2.683430e+08,1.119320e+09,8.201965e+09,85.390363,75.0,10.390363,9.589628e+09,99.837275,...,ลงทุน,9211.127432,4679.609100,50.803869,21.803869,7454.33853,80.927537,22.777537,NaN,NaN
0,งบประมาณรายจ่ายประจำปี พ.ศ.2565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ภาพรวม,1.300302e+04,NaN,4.700026e+02,5.275988e+03,40.575087,NaN,8.575087,5.745991e+03,44.189651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.0,34.08
2,ประจำ,6.822812e+03,NaN,1.270684e+01,3.984779e+03,58.403766,NaN,23.403766,3.997486e+03,58.590007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,35.33
3,ลงทุน,6.180212e+03,NaN,4.572958e+02,1.291209e+03,20.892634,NaN,1.892634,1.748505e+03,28.291989,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,28.96

# HW4
จากตาราง ```sep_oct_df```

1.   งบประมาณประจำหรืองบประมาณลงทุน สูงกว่ากัน
2.   งบรวม เดือน oct หรือ sep อันไหนมากกว่ากัน
3.   แก้ค่า missing พร้อมทั้งให้เหตุผล
4.   เดือนไหนเบิกจ่ายรวมมากกว่ากัน (การใช้จ่าย (PO+เบิกจ่าย))

#ข้อ 1

In [15]:
import pandas as pd
import os

from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/Dataviz2023'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx', header=8, skipfooter=26)
sep_df = sep_df.iloc[-2:,:15]
sep_df['เดือน-ปี'] = len(sep_df)*['sep-65']
sep_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q4,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,เป้า\nหมาย Q4.1,*/- เป้าหมาย.1,คงเหลือ\nหลังหักใช้จ่าย,ลำดับเบิกจ่าย,ลำดับ\nใช้จ่าย,เดือน-ปี
2,ประจำ,1.892013e+10,7.925745e+07,7.131600e+07,1.880196e+10,99.375405,98.0,1.375405,1.895253e+10,100.171242,100.0,0.171242,-3.239918e+07,NaN,NaN,sep-65
3,ลงทุน,9.605258e+09,2.683430e+08,1.119320e+09,8.201965e+09,85.390363,75.0,10.390363,9.589628e+09,99.837275,100.0,-0.162725,1.563013e+07,6.0,15.0,sep-65

In [22]:
oct_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/oct65.xlsx', header=9, skipfooter=27)
oct_df = oct_df.iloc[-2:,:15]
oct_df['เดือน-ปี'] = len(oct_df)*['oct-65']
oct_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q1,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,เป้า\nหมาย Q1.1,*/- เป้าหมาย.1,คงเหลือ\nหลังหักใช้จ่าย,ลำดับเบิกจ่าย,ลำดับ\nใช้จ่าย,เดือน-ปี
2,ประจำ,6822.811789,NaN,12.706842,3984.779058,58.403766,35.0,23.403766,3997.485900,58.590007,35.33,23.260007,2825.325889,NaN,NaN,oct-65
3,ลงทุน,6180.211723,NaN,457.295806,1291.209026,20.892634,19.0,1.892634,1748.504832,28.291989,28.96,-0.668011,4431.706890,4.0,6.0,oct-65

In [24]:
sep_oct_df = pd.concat([sep_df, oct_df])
sep_oct_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละ\nเบิกจ่าย,เป้า\nหมาย Q4,*/- เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละ\nการใช้จ่าย,เป้า\nหมาย Q4.1,*/- เป้าหมาย.1,คงเหลือ\nหลังหักใช้จ่าย,ลำดับเบิกจ่าย,ลำดับ\nใช้จ่าย,เดือน-ปี,เป้า\nหมาย Q1,เป้า\nหมาย Q1.1
2,ประจำ,1.892013e+10,7.925745e+07,7.131600e+07,1.880196e+10,99.375405,98.0,1.375405,1.895253e+10,100.171242,100.0,0.171242,-3.239918e+07,NaN,NaN,sep-65,NaN,NaN
3,ลงทุน,9.605258e+09,2.683430e+08,1.119320e+09,8.201965e+09,85.390363,75.0,10.390363,9.589628e+09,99.837275,100.0,-0.162725,1.563013e+07,6.0,15.0,sep-65,NaN,NaN
2,ประจำ,6.822812e+03,NaN,1.270684e+01,3.984779e+03,58.403766,NaN,23.403766,3.997486e+03,58.590007,NaN,23.260007,2.825326e+03,NaN,NaN,oct-65,35.0,35.33
3,ลงทุน,6.180212e+03,NaN,4.572958e+02,1.291209e+03,20.892634,NaN,1.892634,1.748505e+03,28.291989,NaN,-0.668011,4.431707e+03,4.0,6.0,oct-65,19.0,28.96

In [28]:
fix_sep = sep_oct_df[(sep_oct_df['รายการ']=='ประจำ')&( sep_oct_df['เดือน-ปี']=='sep-65')]['งบประมาณ']
invest_sep = sep_oct_df[(sep_oct_df['รายการ']=='ลงทุน')&( sep_oct_df['เดือน-ปี']=='sep-65')]['งบประมาณ']
fix_oct = sep_oct_df[(sep_oct_df['รายการ']=='ประจำ')&( sep_oct_df['เดือน-ปี']=='oct-65')]['งบประมาณ']
invest_oct = sep_oct_df[(sep_oct_df['รายการ']=='ลงทุน')&( sep_oct_df['เดือน-ปี']=='oct-65')]['งบประมาณ']
if int(fix_sep) > int(invest_sep): print(f'ในเดือนกันยายน งบประมาณประจำ สูงกว่างบประมาณลงทุนอยู่',int(fix_sep)-int(invest_sep),'บาท')
else: print (f'ในเดือนกันยายน งบประมาณลงทุน สูงกว่างบประมาณประจำอยู่',int(invest_sep)-int(fix_sep),'บาท')

if int(fix_oct) > int(invest_oct): print(f'ในเดือนตุลาคม งบประมาณประจำ สูงกว่างบประมาณลงทุนอยู่', int(fix_oct)-int(invest_oct),'บาท')
else: print (f'ในเดือนตุลาคม งบประมาณลงทุน สูงกว่างบประมาณประจำอยู่', int(invest_oct)-int(fix_oct),'บาท')

ในเดือนกันยายน งบประมาณประจำ สูงกว่างบประมาณลงทุนอยู่ 9314873477 บาท
ในเดือนตุลาคม งบประมาณประจำ สูงกว่างบประมาณลงทุนอยู่ 642 บาท

#ข้่อ 2

In [32]:
total_sep = int(fix_sep) + int(invest_sep)
total_oct = int(fix_oct) + int(invest_oct)
if total_sep > total_oct : print(f'งบรวมเดือนกันยายนมากกว่าเดือนตุลาคมอยู่',(total_sep - total_oct), 'บาท')
else: print(f'งบรวมเดือนตุลาคมมากกว่าเดือนกันยายนอยู่',(total_oct - total_sep), 'บาท')

งบรวมเดือนกันยายนมากกว่าเดือนตุลาคมอยู่ 28525376385 บาท

#ข้อ 3

In [34]:
sep_oct_df = pd.concat([sep_df, oct_df])
sep_oct_df.rename(columns=lambda x: x.replace('\n', ''), inplace=True)
sep_oct_df.rename(columns=lambda x: x.replace('*/-', ''), inplace=True)
sep_oct_df.fillna('-', inplace = True)
sep_oct_df

,รายการ,งบประมาณ,สำรองเงินมีหนี้,PO,เบิกจ่าย,ร้อยละเบิกจ่าย,เป้าหมาย Q4,เป้าหมาย,การใช้จ่าย (PO+เบิกจ่าย),ร้อยละการใช้จ่าย,เป้าหมาย Q4.1,เป้าหมาย.1,คงเหลือหลังหักใช้จ่าย,ลำดับเบิกจ่าย,ลำดับใช้จ่าย,เดือน-ปี,เป้าหมาย Q1,เป้าหมาย Q1.1
2,ประจำ,1.892013e+10,79257448.41,7.131600e+07,1.880196e+10,99.375405,98.0,1.375405,1.895253e+10,100.171242,100.0,0.171242,-3.239918e+07,-,-,sep-65,-,-
3,ลงทุน,9.605258e+09,268343006.52,1.119320e+09,8.201965e+09,85.390363,75.0,10.390363,9.589628e+09,99.837275,100.0,-0.162725,1.563013e+07,6.0,15.0,sep-65,-,-
2,ประจำ,6.822812e+03,-,1.270684e+01,3.984779e+03,58.403766,-,23.403766,3.997486e+03,58.590007,-,23.260007,2.825326e+03,-,-,oct-65,35.0,35.33
3,ลงทุน,6.180212e+03,-,4.572958e+02,1.291209e+03,20.892634,-,1.892634,1.748505e+03,28.291989,-,-0.668011,4.431707e+03,4.0,6.0,oct-65,19.0,28.96

#ข้อ 4

In [35]:
PO_sep = sep_oct_df [( sep_oct_df['เดือน-ปี']=='sep-65')]['การใช้จ่าย (PO+เบิกจ่าย)'].sum()
PO_oct = sep_oct_df[( sep_oct_df['เดือน-ปี']=='oct-65')]['การใช้จ่าย (PO+เบิกจ่าย)'].sum()
if int(PO_sep) > int(PO_oct): print(f'เดือนกันยายน เบิกจ่ายรวมมากกว่า เดือนตุลาคมอยู่',int(PO_sep - PO_oct),'บาท')
else: print(f'เดือนตุลาคม เบิกจ่ายรวมมากกว่า เดือนกันยายนอยู่',int(PO_oct - PO_sep),'บาท')

เดือนกันยายน เบิกจ่ายรวมมากกว่า เดือนตุลาคมอยู่ 28542152688 บาท